### ISSUE TITLE
EKS 1.26 cloud watch agent not working on Bottlerocket nodes 

### ISSUE THREAD

**Issue by AndriySidliarskiy** [aws/eks-charts#940]
**Describe the bug**
A concise description of what the bug is.
Cannot run agent on eks 1.26 
**Steps to reproduce**
Run cloud watch agent on EKS 1.26 bottlerocket nodes.

**Environment**

* Chart name:
* Chart version: last
* Kubernetes version: 1.26
* Using EKS (yes/no), if so version?
yes 1.26
**Additional Context**:
ERROR from container 

2023-05-03T14:25:09Z E! manager allocate failed,  mountpoint for  not found
panic: Cannot initiate manager

```
goroutine 111 [running]:
github.com/aws/amazon-cloudwatch-agent/plugins/inputs/cadvisor.(*Cadvisor).Gather(0xc000596090, 0x30d5ce0, 0xc0009296a0, 0xc0005ee768, 0x405895)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/plugins/inputs/cadvisor/cadvisor_linux.go:88 +0x3ed
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc0000e7b80, 0x30d5ce0, 0xc0009296a0, 0x0, 0x0)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/models/running_input.go:115 +0x6d
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1(0xc000057200, 0xc0000e7b80, 0x30d5ce0, 0xc0009296a0)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/agent/agent.go:324 +0x3f
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/agent/agent.go:323 +0x91
```

**Comment by burbaniak** [comment]
I have same issue with AWS EKS 1.26. 
After downgrade to 1.25 (Bottlerocket OS 1.13.5 (aws-k8s-1.25)) cloudwatch-metrics is working.

**Comment by AndriySidliarskiy** [comment]
maybe this is the problem 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/62854979/236759860-cf756c49-2be2-4d22-923e-b195f2635d0d.png">
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-26/

**Comment by jseiser** [comment]
Same issue here

```
NAME                                      READY   STATUS             RESTARTS      AGE
cloudwatch-aws-cloudwatch-metrics-56gt2   1/2     CrashLoopBackOff   5 (72s ago)   4m23s
cloudwatch-aws-cloudwatch-metrics-5cg9j   2/2     Running            0             73s
cloudwatch-aws-cloudwatch-metrics-5nl7b   2/2     Running            0             3m28s
cloudwatch-aws-cloudwatch-metrics-8kzwt   2/2     Running            0             4m23s
cloudwatch-aws-cloudwatch-metrics-m4wpn   2/2     Running            0             4m16s
cloudwatch-aws-cloudwatch-metrics-vmwzp   2/2     Running            0             2m39s
cloudwatch-aws-cloudwatch-metrics-z6g56   2/2     Running            0             3m57s
```

```
❯ kubectl logs pod/cloudwatch-aws-cloudwatch-metrics-56gt2 -n cloudwatch -c aws-cloudwatch-metrics
2023/05/17 17:05:03 I! I! Detected the instance is EC2
2023/05/17 17:05:00 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json ...
/opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json does not exist or cannot read. Skipping it.
2023/05/17 17:05:00 Reading json config file path: /etc/cwagentconfig/..2023_05_17_17_01_52.2453333467/cwagentconfig.json ...
2023/05/17 17:05:00 Find symbolic link /etc/cwagentconfig/..data 
2023/05/17 17:05:00 Find symbolic link /etc/cwagentconfig/cwagentconfig.json 
2023/05/17 17:05:00 Reading json config file path: /etc/cwagentconfig/cwagentconfig.json ...
Valid Json input schema.
2023/05/17 17:05:00 I! attempt to access ECS task metadata to determine whether I'm running in ECS.
2023/05/17 17:05:01 W! retry [0/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/05/17 17:05:02 W! retry [1/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/05/17 17:05:03 W! retry [2/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/05/17 17:05:03 I! access ECS task metadata fail with response unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers), assuming I'm not running in ECS.
No csm configuration found.
No metric configuration found.
Configuration validation first phase succeeded
 
2023/05/17 17:05:03 I! Config has been translated into TOML /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml 
2023-05-17T17:05:03Z I! Starting AmazonCloudWatchAgent 1.247350.0
2023-05-17T17:05:03Z I! AWS SDK log level not set
2023-05-17T17:05:03Z I! Loaded inputs: cadvisor k8sapiserver
2023-05-17T17:05:03Z I! Loaded aggregators: 
2023-05-17T17:05:03Z I! Loaded processors: ec2tagger k8sdecorator
2023-05-17T17:05:03Z I! Loaded outputs: cloudwatchlogs
2023-05-17T17:05:03Z I! Tags enabled: 
2023-05-17T17:05:03Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"ip-10-17-2-241.us-gov-west-1.compute.internal", Flush Interval:1s
2023-05-17T17:05:03Z I! [logagent] starting
2023-05-17T17:05:03Z I! [logagent] found plugin cloudwatchlogs is a log backend
2023-05-17T17:05:03Z I! [processors.ec2tagger] ec2tagger: EC2 tagger has started initialization.
2023-05-17T17:05:03Z E! manager allocate failed,  mountpoint for  not found
panic: Cannot initiate manager

goroutine 117 [running]:
github.com/aws/amazon-cloudwatch-agent/plugins/inputs/cadvisor.(*Cadvisor).Gather(0xc0004906c0, 0x30d5ce0, 0xc000638040, 0xc0001f7f68, 0x405895)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/plugins/inputs/cadvisor/cadvisor_linux.go:88 +0x3ed
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc000100a50, 0x30d5ce0, 0xc000638040, 0x0, 0x0)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/models/running_input.go:115 +0x6d
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1(0xc0007cb1a0, 0xc000100a50, 0x30d5ce0, 0xc000638040)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/agent/agent.go:324 +0x3f
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/agent/agent.go:323 +0x91
```

**Comment by AndriySidliarskiy** [comment]
issue 750 fixed my problem
